functionality:
  name: workflow
  namespace: template
  description: |
    An example pipeline and project template.

  arguments:
    - name: "--input"
      alternatives: [ "-i" ]
      type: file
      required: true
      multiple: true
      multiple_sep: ";"
      description: Input TSV files
      example: file1.tar.gz;file2.tar.gz 
    - name: "--output"
      alternatives: [ "-o" ]
      type: file
      direction: output
      required: true
      description: Output TSV file
      example: output.tsv

  resources:
    - type: nextflow_script
      path: main.nf
      entrypoint: run_wf

  dependencies: 
    - name: template/combine_columns
      repository: local
    - name: template/remove_comments
      repository: local
    - name: template/take_column
      repository: local
    - name: split/expand
      repository: vsh-pipeline-operators
    - name: join/vsh_toList
      repository: vsh-pipeline-operators

  repositories:
    - name: local
      type: local
    - name: vsh-pipeline-operators
      type: vsh
      repo: data-intuitive/vsh-pipeline-operators
      tag: v0.1.0

platforms:
  - type: nextflow
